### ISSUE TITLE
Allow proxying commands

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#148]
In some cases you may want to run grunt commands in a host environment but have the commands executed in a Docker container running on the host (or another environment that has shared file access to the project repo and the user is able to run commands in).

**Comment by grayside** [comment]
Imagining that this would be a special configuration of the grunt-ssh or maybe one of the docker-centric plugins to create a "dispatch" task, here are some initial thoughts:

* I'm calling it dispatch already because of the theme proxying branch claiming that term. Should that one be renamed or are we okay with something other than "proxy" here?
* Need to have the full node/grunt stack installed for the project on your host environment just to get to the dispatching functionality. Seems potentially heavy given the point of docker et al. This seems like it may be in the purview of bash helper scripts. `bin/<container> analyze`?
* If grunt is being configured with SSH credentials for this and URL details for testing, should we consider loading from or generating Drush Site Aliases? fig.yml?

To clarify one final point, I assume we're not trying to implement "trigger a production rebuild from my local environment", that seems bad. Instead, this might be used when SSH'd into a production server to more easily interact with the docker containers holding the application.

**Comment by grayside** [comment]
Closing old issues that I do not expect to be tackled in the context of this project.
