### ISSUE TITLE
Add drush updb and fra as an update task

### ISSUE THREAD

**Issue by peterschuelke** [phase2/grunt-drupal-tasks#156]
I recently experienced a situation where I merged in a branch that contained an update hook. I ran 'grunt'  to rebuild the site, but the site failed due to a missing table column. I think it'd be worth adding an update task that can run on site builds. This would be handy as code is deployed to various environments.

**Comment by grayside** [comment]
Hi @peterschuelke, 

Thanks for your thoughts!

I've been exploring some notions to support more Drupal operations as part of #98, and I'm intermittently pushing forward with it. How to get this right for all or most use cases is surprisingly tricky.

On my projects using GDT I implement a "grunt update" operation that runs `updatedb` and `features-revert-all`.

This needs to stay separate-by-default from the main `grunt` task because we don't want to require a running Drupal site as part of the build process. grunt --update seems like a reasonable opt-in for projects that have an update task.
