### ISSUE TITLE
The 'core' attribute 8.0.x has an incorrect format.

### ISSUE THREAD

**Issue by smerth** [phase2/grunt-drupal-tasks#185]
Grunt aborts with this error message: 

Running "drush:make" (drush) task
The 'core' attribute 8.0.x has an incorrect format.                                                                    [error]
Beginning to build src/project.make.                                                                                   [ok]
No core project specified.                                                                                             [error]
Warning: Drush failed: 1 Use --force to continue.

**Comment by smerth** [comment]
Solution: edit 

core 8.0.x 
to
core = 8.x

Not sure what the ramifications of that change are since the following is also specified:

; Drupal Core
projects[drupal][version] = "8.0.0-beta14"

At least Grunt finishes installing Drupal.

Great, about 5 hours of Googling and trail and error to install Drupal with grunt-drupal-tasks

**Comment by grayside** [comment]
The issue is not about grunt-drupal-tasks, but the makefile created by generator-gadget. Drupal 8 has been implementing a new versioning scheme (semver.org) which is fantastic for it's lifecycle management, but as different pieces are rolled out in practice it's difficult for other tools to keep up.

Sorry you had a frustrating experience but I appreciate you pointing out the latest area for change.
