### ISSUE TITLE
Use composer instead of drush make

### ISSUE THREAD

**Issue by annared** [phase2/grunt-drupal-tasks#313]
Is it possible to manage dependencies with composer instead of drush make? 
(In drupal7)

**Comment by mike-potter** [comment]
The Drupal.org package repository being build here: https://www.drupal.org/node/2718229 will have support for Drupal 7. However, the Composer Manager module might still be needed in Drupal 7 and since Drupal 7 core was never really designed for Composer I'm not sure it really works.  Somebody would need to test it extensively and report.

But that doesn't really affect this GDT project. The latest version supports a project with a drush make file or a project with just a composer.json file. So if you find a composer.json that works with Drupal 7 then you should still be able to use GDT.

**Comment by grayside** [comment]
drush make will not be executed if you delete the srcPaths.make property from your Gruntconfig.json. (as of v1)
